### ISSUE TITLE
2.3 -> 2.4 upgrade breaks SessionAuthenticationPolicy

### ISSUE THREAD

**Issue by hyperknot** [Pylons/pyramid_tm#75]
Upgrading from 2.3 -> 2.4 breaks my app:

```
web/build/venv/lib/python2.7/site-packages/redis/client.py:692: DeprecationWarning: "charset" is deprecated. Use "encoding" instead
  '"charset" is deprecated. Use "encoding" instead'))
web/build/venv/lib/python2.7/site-packages/redis/client.py:696: DeprecationWarning: "errors" is deprecated. Use "encoding_errors" instead
  '"errors" is deprecated. Use "encoding_errors" instead'))
2020-02-19 20:37:29,334 ERROR [waitress] Exception while serving /
Traceback (most recent call last):
  File "web/build/venv/lib/python2.7/site-packages/waitress/channel.py", line 349, in service
    task.service()
  File "web/build/venv/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "web/build/venv/lib/python2.7/site-packages/waitress/task.py", line 439, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "web/build/venv/lib/python2.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "web/build/venv/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "web/build/venv/lib/python2.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "web/build/venv/lib/python2.7/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "web/build/venv/lib/python2.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "web/build/venv/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "web/build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 178, in tm_tween
    reraise(*exc_info)
  File "web/build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 135, in tm_tween
    userid = request.authenticated_userid
  File "web/build/venv/lib/python2.7/site-packages/pyramid/security.py", line 381, in authenticated_userid
    return policy.authenticated_userid(self)
  File "web/app_web/app_web/security.py", line 56, in authenticated_userid
    return request.user.id
AttributeError: 'NoneType' object has no attribute 'id'
```

My piece of code is the following:
```
class CustomSessionAuthenticationPolicy(SessionAuthenticationPolicy):
    def authenticated_userid(self, request):
        return request.user.id

    def effective_principals(self, request):
        principals = [Everyone]
        if request.user:
            principals += [Authenticated]

            if request.user.id == 1:
                principals += ['g:superadmin', 'g:admin']

        return principals
```

Python is 2.7 - I know, I'm hopefully being able to migrate away from it very soon.

**Comment by mmerickel** [comment]
well `request.user` is `None`. The change in 2.4 causes `request.authenticated_userid` to be invoked earlier than you are probably used to. My suggestion is to set `tm.annotate_user = no` in your ini file.

**Comment by hyperknot** [comment]
Thanks, it fixed it.
